version: '3'

services:
  postgres:
    image: postgres:latest
    privileged: true
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres-db:/data/postgres
    networks:
      - backend

  django:
    build: ./django/
    privileged: true
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - postgres
    entrypoint: ${APP_HOME}/entrypoint.sh
    volumes:
      - static_volume:${APP_HOME}/staticfiles
    networks:
      - backend

  fastapi-content-api:
    build: ./content_api/src/
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "8000"
    depends_on:
      - es
      - redis

  fastapi-auth-api:
    build: ./auth_api/src/
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    restart: on-failure
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:${APP_HOME}/staticfiles
    depends_on:
      - django
      - fastapi-auth-api
      - fastapi-content-api
    ports:
      - "80:80"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    privileged: true
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 50

  es-dump:
    image: elasticdump/elasticsearch-dump
    container_name: es-dump
    privileged: true
    networks:
      - backend
    volumes:
      - ./es_index:/es_index
      - ./dump.sh:/dump.sh
    depends_on:
      - es
    command: /bin/sh -c "chmod +x dump.sh 
      && ./dump.sh"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - backend
    volumes:
      - es-db:/data/es

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - backend
    ports:
      - "6831:6831/udp"
      - "16686:16686"

volumes:
  postgres-db:
  es-db:
  static_volume:

networks:
  backend:
